name: frontend
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  google_sign_in: ^6.2.1
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.2
  http: ^1.5.0
  image_picker: ^1.2.0
  io: ^1.0.5
  intl_utils: ^2.8.12
  permission_handler: ^12.0.1
  flutter_blue_plus: ^1.34.5
  flutter_blueprint: ^1.7.1
  esc_pos_bluetooth: ^0.4.1
  esc_pos_printer: ^4.1.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.3.2 
  
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env 
